apiVersion: v1
kind: Service
metadata:
  name: db
  labels:   # This label doesn’t matter.
    name: postgres-service
    app: demo-voting-app
spec:
  type: ClusterIP #default
  ports:
  - targetPort: 5432 	#podPort
    port: 5432 	#serviceListeningPort - it is mandatory
  selector: 	#valuesFromPodLabels
    name: postgres-pod
    app: demo-voting-app
