apiVersion: v1
kind: Service
metadata:
  name: redis
  labels: # This label doesn’t matter.
    name: redis-service
    app: demo-voting-app
spec:
  type: ClusterIP #default
  ports:
  - targetPort: 6379  #podPort
    port: 6379  #serviceListeningPort - it is mandatory
  selector:   #valuesFromPodLabels
    name: redis-pod
    app: demo-voting-app