apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels: # This label doesn’t matter.
    name: voting-app-service
    app: demo-voting-app
spec:
  type: NodePort #default
  ports:
  - targetPort: 80  #podPort
    port: 5000  #serviceListeningPort - it is mandatory
    nodePort: 31000
  selector:   #valuesFromPodLabels
    name: voting-app-pod
    app: demo-voting-app
                      