apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels: # This label doesn’t matter.
    name: voting-app
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: voting-app-pod-name
      labels: # this label matters
        name: voting-app-pod
        app: demo-voting-app
    spec:
      containers:
      - name: voting-app
        image: kodekloud/examplevotingapp_vote:before
        ports:
        - containerPort: 80