apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod-name
  labels:
    name: worker-app-pod
    app: demo-voting-app

spec:
  containers:
  - name: worker-app
    image: kodekloud/examplevotingapp_worker:v1
